@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> GameController: PlayGame()
GameController -> GameController: setup()
GameController -> GameController: CreatePlayers()
GameController -> Language: SetLanguage()
GameController -> GameController: CheckJail()
GameController <-- GameController: CheckJail status
alt CheckJail true
    GameController -> Player: getOutOfJailCard()
    GameController <-- Player: GetOutOfJailCard Status
    alt GetOutOfJailCard false
    GameController -> Player: AddBalance(-1)
    end
    GameController -> Player: setOutOfJailCard(false)
    end
GameController -> Die: ThrowDie:
GameController <-- Die: ThrowDie Resuslt
GameController -> GameController: Moveplayer(Player: player[], die: int)
GameController -> GameController: LandOnField(Player: player[])
alt propertyfield
    GameController -> Player: AddBalance()
    GameController -> Field: setOwner()

@enduml